version: '3.7'

services:
  nuxt3_app:
    container_name: nuxt3_app
    build:
      context: .
      dockerfile: Dockerfile
    image: nuxt3_app:0.0.2
    volumes:
      - '.:/nuxt3-app'
      - '/nuxt3-app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true